title: Hanlin Chen (陈翰林)
url: "https://hlinchen.github.io"
baseurl: "/hlchen"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

# footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

remote_theme: ankitsultana/researcher@gem

nav:
 - name: "About"
   link: "/hlchen/"
 - name: "Curriculum Vitae"
   link: "cv.pdf"
- name: "GitHub"
  link: https://github.com/HLinChen
#  - name: "Contact"
#    link: "contact"
